sudo: false
language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
script:
  - sbt clean coverage test coverageReport &&
    sbt coverageAggregate
after_success:
  - sbt coveralls
  - sbt updateImpactSubmit
